### ISSUE TITLE
install from simplytest.me

### ISSUE THREAD

**Issue by GiorgosK** [drupal-fancy/fancy_kickstart#5]
leads to a problem with database right after confirming the admin/pass timezone etc 
and I am unable to see the demonstration

**Comment by yannickoo** [comment]
> leads to a problem with database

Could you please post a screenshot of that problem?

I cannot reproduce this but I got an notice which was caused by a permission problem with Fancy Grid module.
![screen shot 2014-10-27 at 11 18 44](https://cloud.githubusercontent.com/assets/1086961/4789245/fde22dbe-5dc2-11e4-8447-7c018dc29d3b.png)
![screen shot 2014-10-27 at 11 19 05](https://cloud.githubusercontent.com/assets/1086961/4789246/fde6cbbc-5dc2-11e4-86c8-1636876c38b1.png)
